parameters:
# nothing to declare

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  _instanceof:
    LeoVie\PhpTokenNormalize\TokenNormalizer\TokenNormalizer:
      tags: [ 'app.token_normalizer' ]
  LeoVie\PhpTokenNormalize\Service\TokenSequenceNormalizer:
    arguments: [ !tagged_iterator { tag: 'app.token_normalizer' } ]
    public: true