parameters:
# nothing to declare

services:
  _instanceof:
    LeoVie\PhpTokenNormalize\TokenNormalizer\TokenNormalizer:
      tags: [ 'app.token_normalizer' ]
  LeoVie\PhpTokenNormalize\Service\TokenSequenceNormalizer:
    arguments: [ !tagged_iterator { tag: 'app.token_normalizer' } ]

  LeoVie\PhpTokenNormalize\TokenNormalizer\NothingToNormalizeNormalizer:
    public: true

  app.phptokennormalize.tokennormalizer:
    alias: LeoVie\PhpTokenNormalize\Service\TokenSequenceNormalizer
    public: true