parameters:
# nothing to declare

_defaults:
  autowire: true

services:
  _instanceof:
    LeoVie\PhpTokenNormalize\TokenNormalizer\TokenNormalizer:
      tags: [ 'app.token_normalizer' ]
  LeoVie\PhpTokenNormalize\Service\TokenSequenceNormalizer:
    arguments: [ !tagged_iterator { tag: 'app.token_normalizer' } ]
    public: true