parameters:
# nothing to declare

services:
  LeoVie\PhpTokenNormalize\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/PhpTokenNormalizeBundle.php'
  _instanceof:
    LeoVie\PhpTokenNormalize\TokenNormalizer\TokenNormalizer:
      tags: [ 'app.token_normalizer' ]
  LeoVie\PhpTokenNormalize\TokenNormalizer\TokenNormalizerCollection:
    arguments: [ !tagged_iterator { tag: 'app.token_normalizer' } ]
  LeoVie\PhpTokenNormalize\Service\TokenSequenceNormalizer:
    public: true
    autowire: true